-- MySQL Script generated by MySQL Workbench
-- 2022年07月08日 星期五 15时20分06秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema garage_erp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema garage_erp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garage_erp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `garage_erp` ;

-- -----------------------------------------------------
-- Table `garage_erp`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `role_id` VARCHAR(45) NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `manager_id` INT NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `sector` VARCHAR(45) NULL DEFAULT NULL,
  `file_id` VARCHAR(128) NULL DEFAULT NULL,
  `file_type_id` INT NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `dob` VARCHAR(45) NULL DEFAULT NULL,
  `eid` VARCHAR(45) NULL DEFAULT NULL,
  `driving_license` VARCHAR(45) NULL DEFAULT NULL,
  `passport` VARCHAR(45) NULL DEFAULT NULL,
  `onboarding_date` DATE NULL DEFAULT NULL,
  `photo_path` VARCHAR(256) NULL DEFAULT NULL,
  `visa_expired_date` DATE NULL DEFAULT NULL,
  `contract_expired_date` DATE NULL DEFAULT NULL,
  `salary` FLOAT NULL DEFAULT NULL,
  `employee_id` VARCHAR(45) NULL DEFAULT NULL,
  `total_annual_leave` FLOAT NULL DEFAULT NULL,
  `last_year_leave_balance` FLOAT NULL DEFAULT NULL,
  `score` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `garage_erp`.`t_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(45) NULL DEFAULT NULL,
  `chassis_num` VARCHAR(128) NULL DEFAULT NULL,
  `model` VARCHAR(128) NULL DEFAULT NULL,
  `make` VARCHAR(128) NULL DEFAULT NULL,
  `year` VARCHAR(45) NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `fuel` VARCHAR(45) NULL,
  `last_service_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_car_part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_car_part` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `location` VARCHAR(128) NULL DEFAULT NULL,
  `specialisation` VARCHAR(45) NULL DEFAULT NULL,
  `volume_sale` FLOAT NULL DEFAULT NULL,
  `num_employee` INT NULL DEFAULT NULL,
  `trade_license_path` VARCHAR(256) NULL DEFAULT NULL,
  `logo_path` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_company_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_company_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(125) NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `document_path` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_expense` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(256) NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_expense_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_expense_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_file_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_file_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_income` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `description` VARCHAR(256) NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_income_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_income_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_inspection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_card_id` INT NULL DEFAULT NULL,
  `score` FLOAT NULL DEFAULT NULL,
  `usure_km` FLOAT NULL DEFAULT NULL,
  `comments` VARCHAR(512) NULL DEFAULT NULL,
  `all_operations` TINYINT(1) NULL DEFAULT '0',
  `part_id` INT NULL,
  `image_path` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_inspection_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_inspection_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(512) NULL DEFAULT NULL,
  `inception_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_inspection_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_inspection_points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inspection_point` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_job_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_job_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL DEFAULT NULL,
  `customer_comments` VARCHAR(360) NULL DEFAULT NULL,
  `advisor_comments` VARCHAR(360) NULL DEFAULT NULL,
  `final_comments` VARCHAR(360) NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `assignee_user_id` INT NULL DEFAULT NULL,
  `status` ENUM('pending', 'ongoing', 'pickup', 'done') NULL,
  `pending_comment` VARCHAR(128) NULL,
  `payment_comment` VARCHAR(128) NULL,
  `customer_id` INT NULL,
  `user_id` INT NULL,
  `amount` FLOAT NULL,
  `car_id` INT NULL,
  `mileage` FLOAT NULL,
  `plate` VARCHAR(45) NULL,
  `front_path` VARCHAR(256) NULL,
  `back_path` VARCHAR(256) NULL,
  `body_path` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_job_card_pending_status_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_job_card_pending_status_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_job_card_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_job_card_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(512) NULL DEFAULT NULL,
  `job_card_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_job_card_unfinished_status_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_job_card_unfinished_status_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_kpi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_kpi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `score` FLOAT NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_kpi_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_kpi_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_operation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_card_id` INT NULL DEFAULT NULL,
  `operation_category_id` INT NULL DEFAULT NULL,
  `product` VARCHAR(45) NULL DEFAULT NULL,
  `specification` VARCHAR(45) NULL DEFAULT NULL,
  `service_type` VARCHAR(45) NULL DEFAULT NULL,
  `motor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_operation_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_operation_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_part_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_part_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `part_id` VARCHAR(45) NULL DEFAULT NULL,
  `from_company_id` VARCHAR(45) NULL DEFAULT NULL,
  `to_company_id` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_part_quota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_part_quota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `part_id` INT NULL DEFAULT NULL,
  `labour_hours_amount` INT NULL DEFAULT NULL,
  `part_amount` INT NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  `job_card_id` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `total_price` FLOAT NULL,
  `discount` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Comment Example';


-- -----------------------------------------------------
-- Table `garage_erp`.`t_role_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_role_auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NULL DEFAULT NULL,
  `auth_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_salary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `base` FLOAT NULL DEFAULT NULL,
  `allowance` FLOAT NULL DEFAULT NULL,
  `other` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `days` FLOAT NULL DEFAULT NULL COMMENT 'if leave, this is the days of leave',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_schedule_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_schedule_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `type` ENUM('busy', 'leave', 'available') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_sector` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `company_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_job_card_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_job_card_asset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_card_id` INT NULL,
  `path` VARCHAR(256) NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_make`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_make` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garage_erp`.`t_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garage_erp`.`t_model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `make_id` INT NULL,
  `name` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
